export default {
  screenshot20230807at101342am: require('../assets/images/ScreenShot20230807At101342AM.png'),
  trailtwinlogo: require('../assets/images/TrailTwinLogo.jpg'),
  Avatar: require('../assets/images/Avatar.jpeg'),
  Logo: require('../assets/images/Logo.png'),
  Notifications: require('../assets/images/Notifications.png'),
  User: require('../assets/images/User.png'),
  Edit: require('../assets/images/Edit.png'),
  IconMyChannel: require('../assets/images/IconMyChannel.png'),
  IconSubscriptions: require('../assets/images/IconSubscriptions.png'),
  IconPaymentMethods: require('../assets/images/IconPaymentMethods.png'),
  IconProfile: require('../assets/images/IconProfile.png'),
  IconNotfications: require('../assets/images/IconNotfications.png'),
  IconPreferences: require('../assets/images/IconPreferences.png'),
  IconSecurity: require('../assets/images/IconSecurity.png'),
  IconLanguages: require('../assets/images/IconLanguages.png'),
  IconDarkMode: require('../assets/images/IconDarkMode.png'),
  IconHelp: require('../assets/images/IconHelp.png'),
  IconInvite: require('../assets/images/IconInvite.png'),
  IconCommunity: require('../assets/images/IconCommunity.png'),
  IconTerms: require('../assets/images/IconTerms.png'),
  IconAbout: require('../assets/images/IconAbout.png'),
  IconLogout: require('../assets/images/IconLogout.png'),
  CharlieGreen3JmfENcL24MUnsplash: require('../assets/images/CharlieGreen3JmfENcL24MUnsplash.jpg'),
  ID: require('../assets/images/ID.png'),
};
